app.js
controllers/sat-veg.js
routes/sat-veg.js
services/config.service.js
services/report.service.js
services/view.service.js

Fixed error when searching for data when the analyzes were not complete.

B1.0.0 - Fixed error when searching for data when the analyzes were not complete.

---

services/report.service.js
utils/helpers/report/doc-definition-prodes.js

New fields inserted, fields that can be modified before generating the report. Modified all area values to obtain only 4 decimal places Ndvi that was attached, inserted after image 6.

B1.0.0 - change defDocuments of the PRODES

---

services/report.service.js
utils/helpers/report/doc-definition-prodes.js

Modified values ​​of Consolidated Use; sums of areas, area_ha_car_usocon. inserted in the in the table. Refactor table. Report code and refactored sqls. car_x_usoCon - placed the view as a daughter of the validated car and rename its label Withdrawn old consolidated use that was the son of the validated car AUC values ​​separated by classes and reorganized in the table RADAM vegetation refactored to display in table Deforestation added to table

Modification table in report

---

services/report.service.js
utils/helpers/report/doc-definition-deter.js
utils/helpers/report/doc-definition.js

In the definition of the document, the image of the partners, planet and new table was added.

Refined DETER method and document definition.

---

utils/helpers/report/doc-definition-queimada.js

using unique values for AQC numbers at dinamic text.

Get unique AQC numbers

---

utils/helpers/report/doc-definition-queimada.js

A new style was created to deal with paragraph with leading indentation.
PDFMake has a method called `leadingIndent` that start a paragraph with an indentation, then, i made a new style called "bodyIndentFirst".
PDFMake - `leadingIndent` docs [here](https://github.com/bpampuch/pdfmake/pull/1054)

New way to work with paragraph and lead indentation

---

utils/helpers/report/doc-definition-queimada.js

Inserting, styling and placing footnotes.

Inserting footnotes

---

services/report.service.js
utils/helpers/report/doc-definition-queimada.js

Removing the second chart from  report...
its data was included in the first chart.
issue #235

Removing the second chart from report.

---

services/report.service.js
utils/helpers/report/doc-definition-queimada.js

Getting conclusion paragraph and inserting in report.

Insert conslusion paragraph

---

services/view.service.js
utils/helpers/views/burned.js
utils/helpers/views/filter/burned.filter.js

Updated layer CAR x FOCOS to show CAR polygons instead of points

Updated layer CAR x FOCOS

---

services/geoServer.service.js
utils/helpers/geoserver/burned.filter.js

Modifying fire filter x projus to default, and inserting correct query dynamically.

Correcting filter, removing project filter and changing it to default

---

utils/helpers/report/doc-definition-queimada.js

Getting `null` when `reportData.property.registry` is null... now it will use `reportData.property.federalregistry` instead.
Fix report identation;
Fix item `3 Metodo utilizado` position;
Fix space before item `CONCLUSION`;

Fixing some issues at burning report

---

package-lock.json
package.json

Adding 2.0.0- to version key at package.json.
Some updates from node.

Adding 2.0.0- to version key at package.json

---

controllers/group.controller.js
migrations/20210108031319-create-group.js
migrations/20210108143800-create-rel-group-view.js
models/group.js
models/rel-group-view.model.js
routes/group.router.js
services/group.service.js

Creating new endpoints to group routes.

Group routes

---

controllers/group-view.controller.js
models/rel-group-view.model.js
services/group-view.service.js
services/group.service.js

modifying the update method so that it receives or group id delete the information contained in it, to insert the values ​​of the selected layers

modifying the update method so that it receives or group id delete the information contained in it

---

services/group-view.service.js

Inserting all selected groups into the database

Inserting the selected groups into the database

---

services/geoServer.service.js

fix updateDataStore

---

services/geoServer.service.js
services/report.service.js
utils/helpers/report/doc-definition-prodes.js

Fix some spaces..
refactoring some functions
removing getContextDesflorestationHistory that was not being used.

Prodes changes

---

services/geoServer.service.js
services/report.service.js
utils/helpers/report/doc-definition-prodes.js

fix some issues at prodes report.
New object at resultReportData to get report layers and filters

Fix report issues and create a new key to help to dowload report vectors layers

---

services/report.service.js
utils/helpers/report/doc-definition-prodes.js

Updating report text with MPMT proposal
